// Auto-generated by build_data.py - do not edit by hand.
const DASHBOARD_DATA = {
  "generatedFrom": [
    "MOVE Fund Eval - Salem_June 22, 2026_13.41.csv",
    "MOVE Fund Eval - DC_June 22, 2026_14.02.csv"
  ],
  "coalitions": [
    "Salem",
    "DC"
  ],
  "timepoints": [
    "T1"
  ],
  "scaleMax": 5,
  "constructs": [
    {
      "key": "TACT",
      "name": "Motivation: Tactical",
      "scale": "agreement",
      "items": [
        "TACT_1",
        "TACT_2",
        "TACT_3"
      ]
    },
    {
      "key": "TRAN",
      "name": "Motivation: Transformational",
      "scale": "agreement",
      "items": [
        "TRAN_1",
        "TRAN_2",
        "TRAN_3"
      ]
    },
    {
      "key": "GC",
      "name": "Goal Consensus",
      "scale": "agreement",
      "items": [
        "GC_1",
        "GC_2",
        "GC_3"
      ]
    },
    {
      "key": "COM",
      "name": "Communication",
      "scale": "agreement",
      "items": [
        "COM_1",
        "COM_2",
        "COM_3"
      ]
    },
    {
      "key": "COH",
      "name": "Cohesion",
      "scale": "agreement",
      "items": [
        "COH_1",
        "COH_2",
        "COH_3"
      ]
    },
    {
      "key": "TF",
      "name": "Task Focus",
      "scale": "agreement",
      "items": [
        "TF_1",
        "TF_2",
        "TF_3"
      ]
    },
    {
      "key": "DM",
      "name": "Decision-Making",
      "scale": "frequency",
      "items": [
        "DM_1",
        "DM_2",
        "DM_3"
      ]
    },
    {
      "key": "LEAD",
      "name": "Leadership",
      "scale": "agreement",
      "items": [
        "LEAD_1",
        "LEAD_2",
        "LEAD_3"
      ]
    },
    {
      "key": "STAFF",
      "name": "Staff",
      "scale": "agreement",
      "items": [
        "STAFF_1",
        "STAFF_2",
        "STAFF_3"
      ]
    },
    {
      "key": "TRUST",
      "name": "Trust",
      "scale": "agreement",
      "items": [
        "TRUST_1",
        "TRUST_2",
        "TRUST_3"
      ]
    },
    {
      "key": "MemEng_Sat",
      "name": "Member Engagement",
      "scale": "agreement",
      "items": [
        "MemEng_Sat_1",
        "MemEng_Sat_2",
        "MemEng_Sat_3"
      ]
    },
    {
      "key": "PROD",
      "name": "Productivity",
      "scale": "agreement",
      "items": [
        "PROD_1",
        "PROD_2",
        "PROD_3"
      ]
    },
    {
      "key": "LEGIT",
      "name": "External Legitimacy",
      "scale": "agreement",
      "items": [
        "LEGIT_1",
        "LEGIT_2",
        "LEGIT_3"
      ]
    },
    {
      "key": "AGENDA",
      "name": "Common Agenda",
      "scale": "agreement",
      "items": [
        "AGENDA_1",
        "AGENDA_2",
        "AGENDA_3"
      ]
    },
    {
      "key": "MA",
      "name": "Mutually Reinforcing Activities",
      "scale": "agreement",
      "items": [
        "MA_1",
        "MA_2",
        "MA_3"
      ]
    },
    {
      "key": "SM",
      "name": "Shared Measurement",
      "scale": "agreement",
      "items": [
        "SM_1",
        "SM_2",
        "SM_3"
      ]
    },
    {
      "key": "EQUITY",
      "name": "Equity",
      "scale": "agreement",
      "items": [
        "EQUITY_1",
        "EQUITY_2",
        "EQUITY_3"
      ]
    },
    {
      "key": "OC",
      "name": "Organizational Capacity",
      "scale": "positivity",
      "items": [
        "OC_I_1",
        "OC_G_2",
        "OC_O_3",
        "OC_C_4"
      ]
    },
    {
      "key": "SC",
      "name": "Systems Change",
      "scale": "agreement",
      "items": [
        "SC_1",
        "SC_2",
        "SC_3",
        "SC_4",
        "SC_5",
        "SC_6"
      ]
    },
    {
      "key": "O",
      "name": "Social Outcomes",
      "scale": "agreement",
      "items": [
        "O_1",
        "O_2"
      ]
    }
  ],
  "questionText": {
    "TACT_1": "Motivation to Join: Organizations join Alliances for many reasons. The following questions are focused on understanding what motivated your organization to join the Salem Youth Sports Alliance.\n\n \n\nPlease rate your agreement with the following statements.\n\n \n\nMy organization joined the Salem Youth Sports  Alliance to... - Gain access to new funding opportunities",
    "TACT_2": "Motivation to Join: Organizations join Alliances for many reasons. The following questions are focused on understanding what motivated your organization to join the Salem Youth Sports Alliance.\n\n \n\nPlease rate your agreement with the following statements.\n\n \n\nMy organization joined the Salem Youth Sports  Alliance to... - Operate more efficiently (ex., reduce costs through collaboration)",
    "TACT_3": "Motivation to Join: Organizations join Alliances for many reasons. The following questions are focused on understanding what motivated your organization to join the Salem Youth Sports Alliance.\n\n \n\nPlease rate your agreement with the following statements.\n\n \n\nMy organization joined the Salem Youth Sports  Alliance to... - Expand our program services",
    "TRAN_1": "Motivation to Join: Organizations join Alliances for many reasons. The following questions are focused on understanding what motivated your organization to join the Salem Youth Sports Alliance.\n\n \n\nPlease rate your agreement with the following statements.\n\n \n\nMy organization joined the Salem Youth Sports  Alliance to... - Engage with critical issues facing the community",
    "TRAN_2": "Motivation to Join: Organizations join Alliances for many reasons. The following questions are focused on understanding what motivated your organization to join the Salem Youth Sports Alliance.\n\n \n\nPlease rate your agreement with the following statements.\n\n \n\nMy organization joined the Salem Youth Sports  Alliance to... - Address complex social problems that one organization cannot solve on its own",
    "TRAN_3": "Motivation to Join: Organizations join Alliances for many reasons. The following questions are focused on understanding what motivated your organization to join the Salem Youth Sports Alliance.\n\n \n\nPlease rate your agreement with the following statements.\n\n \n\nMy organization joined the Salem Youth Sports  Alliance to... - Create a system for change or system of program delivery where none existed before",
    "GC_1": "Goal Consensus: Goal consensus relates to the degree to which organizations agree on network-level goals. The following questions are focused on understanding the degree of goal consensus among organizations involved in the Salem Youth Sports Alliance.\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance has clearly defined the problem that it wishes to address",
    "GC_2": "Goal Consensus: Goal consensus relates to the degree to which organizations agree on network-level goals. The following questions are focused on understanding the degree of goal consensus among organizations involved in the Salem Youth Sports Alliance.\n\n\n\nPlease rate your agreement with the following statements. - Member organizations agree upon the overall goals and objectives of the Salem Youth Sports  Alliance",
    "GC_3": "Goal Consensus: Goal consensus relates to the degree to which organizations agree on network-level goals. The following questions are focused on understanding the degree of goal consensus among organizations involved in the Salem Youth Sports Alliance.\n\n\n\nPlease rate your agreement with the following statements. - There is clarity on the vision for where the Salem Youth Sports  Alliance should be going",
    "COM_1": "Communication: Communication relates to the quality of interactions between organizations in the Salem Youth Sports Alliance. The following questions are focused on the level of continuous communication associated with the Salem Youth Sports Alliance.\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance has established a system of communication for member organizations to discuss their efforts",
    "COM_2": "Communication: Communication relates to the quality of interactions between organizations in the Salem Youth Sports Alliance. The following questions are focused on the level of continuous communication associated with the Salem Youth Sports Alliance.\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance provides a safe environment in which disagreements and conflicts can be discussed",
    "COM_3": "Communication: Communication relates to the quality of interactions between organizations in the Salem Youth Sports Alliance. The following questions are focused on the level of continuous communication associated with the Salem Youth Sports Alliance.\n\n\n\nPlease rate your agreement with the following statements. - Communication among organizations in the Salem Youth Sports  Alliance is effective (i.e., promotes understanding, cooperation, and transfer of information)",
    "COH_1": "Cohesion: Cohesion relates to the sense of unity and togetherness among organizations involved in the Salem Youth Sports Alliance. The following questions are focused on the level of cohesion associated with the Salem Youth Sports Alliance.\n\n\n\nPlease rate your agreement with the following statements. - There is a strong feeling of unity and cohesion in the Salem Youth Sports  Alliance",
    "COH_2": "Cohesion: Cohesion relates to the sense of unity and togetherness among organizations involved in the Salem Youth Sports Alliance. The following questions are focused on the level of cohesion associated with the Salem Youth Sports Alliance.\n\n\n\nPlease rate your agreement with the following statements. - There is a strong feeling of belonging in the Salem Youth Sports  Alliance",
    "COH_3": "Cohesion: Cohesion relates to the sense of unity and togetherness among organizations involved in the Salem Youth Sports Alliance. The following questions are focused on the level of cohesion associated with the Salem Youth Sports Alliance.\n\n\n\nPlease rate your agreement with the following statements. - My organization is proud to be a part of the Salem Youth Sports  Alliance",
    "TF_1": "Task Focus: Task Focus relates to the ability of a Alliance to remain focused on achieving practical tasks. The following questions are focused on the degree to which the Salem Youth Sports  Alliance is task focused.\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance supports tasks and activities that serve a practical purpose for member organizations",
    "TF_2": "Task Focus: Task Focus relates to the ability of a Alliance to remain focused on achieving practical tasks. The following questions are focused on the degree to which the Salem Youth Sports  Alliance is task focused.\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance rarely has anything concrete to show for its efforts",
    "TF_3": "Task Focus: Task Focus relates to the ability of a Alliance to remain focused on achieving practical tasks. The following questions are focused on the degree to which the Salem Youth Sports  Alliance is task focused.\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance stays on task",
    "DM_1": "Decision-Making: Decision-making relates to the involvement of organizations in collective decision-making processes. The following questions are focused on your organization's involvement in decision-making processes related to the Salem Youth Sports  Alliance.\n\n\n\nHow much influence does your organization have on making the following types of decisions for the Salem Youth Sports  Alliance? - Setting goals and objectives for the Salem Youth Sports  Alliance",
    "DM_2": "Decision-Making: Decision-making relates to the involvement of organizations in collective decision-making processes. The following questions are focused on your organization's involvement in decision-making processes related to the Salem Youth Sports  Alliance.\n\n\n\nHow much influence does your organization have on making the following types of decisions for the Salem Youth Sports  Alliance? - Determining what activities to prioritize for the Salem Youth Sports  Alliance",
    "DM_3": "Decision-Making: Decision-making relates to the involvement of organizations in collective decision-making processes. The following questions are focused on your organization's involvement in decision-making processes related to the Salem Youth Sports  Alliance.\n\n\n\nHow much influence does your organization have on making the following types of decisions for the Salem Youth Sports  Alliance? - How the Salem Youth Sports  Alliance functions overall",
    "LEAD_1": "Please rate your agreement with the following statements.\nThe Salem Youth Sports  Alliance leadership... - Has a clear vision for the Salem Youth Sports  Alliance",
    "LEAD_2": "Please rate your agreement with the following statements.\nThe Salem Youth Sports  Alliance leadership... - Is respected in the community",
    "LEAD_3": "Please rate your agreement with the following statements.\nThe Salem Youth Sports  Alliance leadership... - Intentionally seeks out the views of member organizations",
    "STAFF_1": "Please rate your agreement with the following statements.\nThe Salem Youth Sports  Alliance staff... - Is competent",
    "STAFF_2": "Please rate your agreement with the following statements.\nThe Salem Youth Sports  Alliance staff... - Works well with collaborative members",
    "STAFF_3": "Please rate your agreement with the following statements.\nThe Salem Youth Sports  Alliance staff... - Shares responsibility for the initiative with organizations in the collaborative",
    "TRUST_1": "Trust: Trust relates to the willingness of organizations to accept vulnerability based on positive expectations about other organization's intentions or behavior. The following questions are focused on your organization's trust in the Salem Youth Sports  Alliance.\n\n\n\nPlease rate your agreement with the following statements. - My organization has an understanding and respect for the Salem Youth Sports  Alliance",
    "TRUST_2": "Trust: Trust relates to the willingness of organizations to accept vulnerability based on positive expectations about other organization's intentions or behavior. The following questions are focused on your organization's trust in the Salem Youth Sports  Alliance.\n\n\n\nPlease rate your agreement with the following statements. - My organization trusts the Salem Youth Sports  Alliance",
    "TRUST_3": "Trust: Trust relates to the willingness of organizations to accept vulnerability based on positive expectations about other organization's intentions or behavior. The following questions are focused on your organization's trust in the Salem Youth Sports  Alliance.\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance carries out its role with fairness",
    "MemEng_Sat_1": "Member Engagement: Member engagement is the process by which member organizations are empowered and develop a sense of belonging to a Alliance. The following questions are focused on your organization's perceptions of member engagement with the Salem Youth Sports  Alliance. Note: these questions are reverse-worded!\n\n\n\nPlease rate your agreement with the following statements. - Power and control are in the hands of a few individuals in the Salem Youth Sports  Alliance",
    "MemEng_Sat_2": "Member Engagement: Member engagement is the process by which member organizations are empowered and develop a sense of belonging to a Alliance. The following questions are focused on your organization's perceptions of member engagement with the Salem Youth Sports  Alliance. Note: these questions are reverse-worded!\n\n\n\nPlease rate your agreement with the following statements. - Members of the Salem Youth Sports  Alliance are not always open with information and honest about their motives",
    "MemEng_Sat_3": "Member Engagement: Member engagement is the process by which member organizations are empowered and develop a sense of belonging to a Alliance. The following questions are focused on your organization's perceptions of member engagement with the Salem Youth Sports  Alliance. Note: these questions are reverse-worded!\n\n\n\nPlease rate your agreement with the following statements. - Some Salem Youth Sports  Alliance members are guarded about putting their ideas forward for discussion",
    "PROD_1": "Productivity: Productivity relates to the tangible benefits derived from being involved in the Alliance. The following questions are focused on your organization's perceptions of the productivity of the Salem Youth Sports  Alliance. Note: these questions are reverse-worded!\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance often fails to meet its goals",
    "PROD_2": "Productivity: Productivity relates to the tangible benefits derived from being involved in the Alliance. The following questions are focused on your organization's perceptions of the productivity of the Salem Youth Sports  Alliance. Note: these questions are reverse-worded!\n\n\n\nPlease rate your agreement with the following statements. - There is a lot of inefficiency in the way the Salem Youth Sports  Alliance uses resources",
    "PROD_3": "Productivity: Productivity relates to the tangible benefits derived from being involved in the Alliance. The following questions are focused on your organization's perceptions of the productivity of the Salem Youth Sports  Alliance. Note: these questions are reverse-worded!\n\n\n\nPlease rate your agreement with the following statements. - There are a lot of wasted resources in the Salem Youth Sports  Alliance",
    "LEGIT_1": "External legitimacy: External legitimacy relates to the ability of a Alliance to establish the external \"face\" of a network that attracts the attention of funders, partners, and community groups that might otherwise be difficult for any single organization. The following questions are focused on your organization's perceptions of the external legitimacy of the Salem Youth Sports  Alliance.\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance commands the respect of a broader group of external stakeholders and can bring key decision-makers to the table",
    "LEGIT_2": "External legitimacy: External legitimacy relates to the ability of a Alliance to establish the external \"face\" of a network that attracts the attention of funders, partners, and community groups that might otherwise be difficult for any single organization. The following questions are focused on your organization's perceptions of the external legitimacy of the Salem Youth Sports  Alliance.\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance has external supporters outside the Alliance who can champion their strategy with the broader community",
    "LEGIT_3": "External legitimacy: External legitimacy relates to the ability of a Alliance to establish the external \"face\" of a network that attracts the attention of funders, partners, and community groups that might otherwise be difficult for any single organization. The following questions are focused on your organization's perceptions of the external legitimacy of the Salem Youth Sports  Alliance.\n\n\n\nPlease rate your agreement with the following statements. - The Salem Youth Sports  Alliance has the ability to shift both public and private funds around targeted issues",
    "AGENDA_1": "Please rate your agreement with the following statements - Organizations involved in the Salem Youth Sports  Alliance understand and can articulate the overarching problem",
    "AGENDA_2": "Please rate your agreement with the following statements - Organizations involved in the Salem Youth Sports  Alliance can accurately describe the main goals of the common agenda",
    "AGENDA_3": "Please rate your agreement with the following statements - Organizations involved in the Salem Youth Sports  Alliance show commitment to the common agenda",
    "MA_1": "Mutually Reinforcing Activities: Mutually reinforcing activities refer to how Alliances help coordinate the activities and initiatives of organizations to mutually reinforce a common agenda. The following questions are focused on the extent to which the activities of organizations in the Salem Youth Sports  Alliance are mutually reinforcing.\n\n\n\nPlease rate your agreement with the following statements - The collaborative structures of the Salem Youth Sports  Alliance (ex., working groups, committees, action teams) helps coordinate activities in alignment with the common agenda",
    "MA_2": "Mutually Reinforcing Activities: Mutually reinforcing activities refer to how Alliances help coordinate the activities and initiatives of organizations to mutually reinforce a common agenda. The following questions are focused on the extent to which the activities of organizations in the Salem Youth Sports  Alliance are mutually reinforcing.\n\n\n\nPlease rate your agreement with the following statements - Our organization has clear approaches/goals for our own contribution to the common agenda",
    "MA_3": "Mutually Reinforcing Activities: Mutually reinforcing activities refer to how Alliances help coordinate the activities and initiatives of organizations to mutually reinforce a common agenda. The following questions are focused on the extent to which the activities of organizations in the Salem Youth Sports  Alliance are mutually reinforcing.\n\n\n\nPlease rate your agreement with the following statements - The individual activities of our organization are changing to better align with the common agenda.",
    "SM_1": "Please rate your agreement with the following statements - My organization sees value in the shared measurement system used by the Salem Youth Sports  Alliance",
    "SM_2": "Please rate your agreement with the following statements - A participatory process is used to determine the common set of indicators and data collection methods used by the Salem Youth Sports  Alliance",
    "SM_3": "Please rate your agreement with the following statements - The common set of indicators and data collection methods provide timely evidence of (or lack of) progress toward the intended outcomes of the Salem Youth Sports  Alliance",
    "EQUITY_1": "Equity: Equity relates to the fairness and justice achieved through systematically assessing disparities in opportunities, outcomes, and representation and redressing those disparities through targeted actions. The following questions ask about how equity is centered in the work of the Salem Youth Sports  Alliance.\n\n\n\nPlease rate your agreement with the following statements - Members of the community help shape the goals and objectives of the Salem Youth Sports  Alliance",
    "EQUITY_2": "Equity: Equity relates to the fairness and justice achieved through systematically assessing disparities in opportunities, outcomes, and representation and redressing those disparities through targeted actions. The following questions ask about how equity is centered in the work of the Salem Youth Sports  Alliance.\n\n\n\nPlease rate your agreement with the following statements - Members of the community are involved in deciding what activities the Salem Youth Sports  Alliance prioritizes",
    "EQUITY_3": "Equity: Equity relates to the fairness and justice achieved through systematically assessing disparities in opportunities, outcomes, and representation and redressing those disparities through targeted actions. The following questions ask about how equity is centered in the work of the Salem Youth Sports  Alliance.\n\n\n\nPlease rate your agreement with the following statements - Members of the community help determine how success is defined and measured by the Salem Youth Sports  Alliance",
    "OC_I_1": "Organizational Capacity: Organizational capacity relates to the ability of an organization to acquire and utilize resources to achieve desired outcomes. The following questions ask about how the Salem Youth Sports  Alliance has influenced the capacity of your organization.\n\n\n\nWhat impact has the Salem Youth Sports  Alliance had on... - Your organizations' ability to recruit qualified staff and volunteers.",
    "OC_G_2": "Organizational Capacity: Organizational capacity relates to the ability of an organization to acquire and utilize resources to achieve desired outcomes. The following questions ask about how the Salem Youth Sports  Alliance has influenced the capacity of your organization.\n\n\n\nWhat impact has the Salem Youth Sports  Alliance had on... - Strengthening the \"community of practice\" in your geographic area (i.e., regularly interacting individuals who share a similar repertoire and are bound together by their engagement in similar goals)",
    "OC_O_3": "Organizational Capacity: Organizational capacity relates to the ability of an organization to acquire and utilize resources to achieve desired outcomes. The following questions ask about how the Salem Youth Sports  Alliance has influenced the capacity of your organization.\n\n\n\nWhat impact has the Salem Youth Sports  Alliance had on... - Securing adequate resources to support your organizations' goals and objectives",
    "OC_C_4": "Organizational Capacity: Organizational capacity relates to the ability of an organization to acquire and utilize resources to achieve desired outcomes. The following questions ask about how the Salem Youth Sports  Alliance has influenced the capacity of your organization.\n\n\n\nWhat impact has the Salem Youth Sports  Alliance had on... - Mobilizing resources that support the community",
    "SC_1": "Systems Change: Systems change can be broadly defined as shifting the conditions that are holding the problem in place. The following questions ask about the influence the Salem Youth Sports  Alliance has had on systems change.\n\n\n\nPlease rate your agreement with the following statements\n\n \n\nThe Salem Youth Sports  Alliance has... - Gained influence over key public and policy decisions that impact sport, recreation, and play equity (e.g. ordinances, ballot-measures, legislation)",
    "SC_2": "Systems Change: Systems change can be broadly defined as shifting the conditions that are holding the problem in place. The following questions ask about the influence the Salem Youth Sports  Alliance has had on systems change.\n\n\n\nPlease rate your agreement with the following statements\n\n \n\nThe Salem Youth Sports  Alliance has... - Improved the quality of sport, recreation, and play services provided to our target population(s)",
    "SC_3": "Systems Change: Systems change can be broadly defined as shifting the conditions that are holding the problem in place. The following questions ask about the influence the Salem Youth Sports  Alliance has had on systems change.\n\n\n\nPlease rate your agreement with the following statements\n\n \n\nThe Salem Youth Sports  Alliance has... - Increased overall funding (government, foundation, contract) for the system of sport, recreation, and play",
    "SC_4": "Systems Change: Systems change can be broadly defined as shifting the conditions that are holding the problem in place. The following questions ask about the influence the Salem Youth Sports  Alliance has had on systems change.\n\n\n\nPlease rate your agreement with the following statements\n\n \n\nThe Salem Youth Sports  Alliance has... - Strengthened relations among key system actors needed to advance sport, recreation, and play equity (e.g, non-profit leaders, public officials, policymakers, healthcare, education)",
    "SC_5": "Systems Change: Systems change can be broadly defined as shifting the conditions that are holding the problem in place. The following questions ask about the influence the Salem Youth Sports  Alliance has had on systems change.\n\n\n\nPlease rate your agreement with the following statements\n\n \n\nThe Salem Youth Sports  Alliance has... - Empowered communities to advocate for their own needs and preferences when it comes to sport, recreation, and play",
    "SC_6": "Systems Change: Systems change can be broadly defined as shifting the conditions that are holding the problem in place. The following questions ask about the influence the Salem Youth Sports  Alliance has had on systems change.\n\n\n\nPlease rate your agreement with the following statements\n\n \n\nThe Salem Youth Sports  Alliance has... - Elevated the importance of equity in sport, recreation, and play to a broader group of stakeholders.",
    "O_1": "Social Outcomes: Outcomes provide indicators of the effectiveness of a Alliance in improving targeted outcomes. The following questions ask about your organization's perception of the impact of the Salem Youth Sports  Alliance on promoting sport, recreation, and play equity in Salem.\n\n\n\nPlease rate your agreement with the following statements - The Salem Youth Sports  Alliance has improved sport, recreation, and play equity in Salem",
    "O_2": "Social Outcomes: Outcomes provide indicators of the effectiveness of a Alliance in improving targeted outcomes. The following questions ask about your organization's perception of the impact of the Salem Youth Sports  Alliance on promoting sport, recreation, and play equity in Salem.\n\n\n\nPlease rate your agreement with the following statements - Youth and families in Salem are better off because of the Salem Youth Sports  Alliance"
  },
  "programFields": [
    {
      "key": "youth_served",
      "label": "Youth served (last 12 mo.)",
      "agg": "sum"
    },
    {
      "key": "pct_aid",
      "label": "% of youth receiving financial aid",
      "agg": "wmean"
    },
    {
      "key": "aid_dollars",
      "label": "Financial aid disbursed ($)",
      "agg": "sum"
    },
    {
      "key": "coaches_worked",
      "label": "Coaches worked",
      "agg": "sum"
    },
    {
      "key": "coaches_trained",
      "label": "Coaches trained",
      "agg": "sum"
    }
  ],
  "cells": {
    "Salem||T1": {
      "TACT": {
        "mean": 3.185,
        "sd": 0.784,
        "n": 9
      },
      "TRAN": {
        "mean": 4.593,
        "sd": 0.722,
        "n": 9
      },
      "GC": {
        "mean": 4.037,
        "sd": 0.539,
        "n": 9
      },
      "COM": {
        "mean": 4.333,
        "sd": 0.687,
        "n": 9
      },
      "COH": {
        "mean": 4.519,
        "sd": 0.377,
        "n": 9
      },
      "TF": {
        "mean": 3.407,
        "sd": 0.222,
        "n": 9
      },
      "DM": {
        "mean": 3.037,
        "sd": 1.099,
        "n": 9
      },
      "LEAD": {
        "mean": 3.944,
        "sd": 0.712,
        "n": 6
      },
      "STAFF": {
        "mean": 4.583,
        "sd": 0.419,
        "n": 4
      },
      "TRUST": {
        "mean": 4.63,
        "sd": 0.423,
        "n": 9
      },
      "MemEng_Sat": {
        "mean": 2.296,
        "sd": 0.676,
        "n": 9
      },
      "PROD": {
        "mean": 2.037,
        "sd": 0.696,
        "n": 9
      },
      "LEGIT": {
        "mean": 3.111,
        "sd": 0.928,
        "n": 9
      },
      "AGENDA": {
        "mean": 3.714,
        "sd": 0.756,
        "n": 7
      },
      "MA": {
        "mean": 4.0,
        "sd": 0.694,
        "n": 7
      },
      "SM": {
        "mean": 4.333,
        "sd": 0.577,
        "n": 3
      },
      "EQUITY": {
        "mean": 3.111,
        "sd": 1.258,
        "n": 9
      },
      "OC": {
        "mean": 3.639,
        "sd": 0.639,
        "n": 9
      },
      "SC": {
        "mean": 3.37,
        "sd": 0.681,
        "n": 9
      },
      "O": {
        "mean": 3.944,
        "sd": 0.768,
        "n": 9
      }
    },
    "DC||T1": {
      "TACT": {
        "mean": 4.056,
        "sd": 0.759,
        "n": 24
      },
      "TRAN": {
        "mean": 3.722,
        "sd": 1.001,
        "n": 24
      },
      "GC": {
        "mean": 4.0,
        "sd": 0.681,
        "n": 24
      },
      "COM": {
        "mean": 3.903,
        "sd": 0.807,
        "n": 24
      },
      "COH": {
        "mean": 4.472,
        "sd": 0.572,
        "n": 24
      },
      "TF": {
        "mean": 3.389,
        "sd": 0.468,
        "n": 24
      },
      "DM": {
        "mean": 2.212,
        "sd": 1.021,
        "n": 22
      },
      "LEAD": {
        "mean": 4.407,
        "sd": 0.672,
        "n": 18
      },
      "STAFF": {
        "mean": 4.45,
        "sd": 0.533,
        "n": 20
      },
      "TRUST": {
        "mean": 4.569,
        "sd": 0.705,
        "n": 24
      },
      "MemEng_Sat": {
        "mean": 2.597,
        "sd": 0.851,
        "n": 24
      },
      "PROD": {
        "mean": 2.246,
        "sd": 0.848,
        "n": 23
      },
      "LEGIT": {
        "mean": 4.087,
        "sd": 0.786,
        "n": 23
      },
      "AGENDA": {
        "mean": 4.167,
        "sd": 0.667,
        "n": 16
      },
      "MA": {
        "mean": 3.922,
        "sd": 0.778,
        "n": 17
      },
      "SM": {
        "mean": 4.0,
        "sd": 0.333,
        "n": 3
      },
      "EQUITY": {
        "mean": 3.542,
        "sd": 0.785,
        "n": 24
      },
      "OC": {
        "mean": 3.815,
        "sd": 0.649,
        "n": 23
      },
      "SC": {
        "mean": 3.964,
        "sd": 0.638,
        "n": 23
      },
      "O": {
        "mean": 4.479,
        "sd": 0.729,
        "n": 24
      }
    }
  },
  "grandMeans": {
    "T1": {
      "TACT": 3.62,
      "TRAN": 4.157,
      "GC": 4.018,
      "COM": 4.118,
      "COH": 4.495,
      "TF": 3.398,
      "DM": 2.625,
      "LEAD": 4.175,
      "STAFF": 4.517,
      "TRUST": 4.599,
      "MemEng_Sat": 2.446,
      "PROD": 2.141,
      "LEGIT": 3.599,
      "AGENDA": 3.941,
      "MA": 3.961,
      "SM": 4.167,
      "EQUITY": 3.327,
      "OC": 3.727,
      "SC": 3.667,
      "O": 4.212
    }
  },
  "program": {
    "Salem||T1": {
      "youth_served": {
        "value": 59462.0,
        "n": 10,
        "raw": [
          {
            "raw": "36",
            "value": 36.0,
            "conf": "ok"
          },
          {
            "raw": "2646",
            "value": 2646.0,
            "conf": "ok"
          },
          {
            "raw": "2000+",
            "value": 2000.0,
            "conf": "approx"
          },
          {
            "raw": "1500 Gymnastics, 60 Preschool and hundreds of youth for indoor play park",
            "value": 1500.0,
            "conf": "approx"
          },
          {
            "raw": "approximately 500- 700",
            "value": 600.0,
            "conf": "approx"
          },
          {
            "raw": "Around 80 youth",
            "value": 80.0,
            "conf": "approx"
          },
          {
            "raw": "1,600",
            "value": 1600.0,
            "conf": "ok"
          },
          {
            "raw": "7000",
            "value": 7000.0,
            "conf": "ok"
          },
          {
            "raw": "approximately 37,000",
            "value": 37000.0,
            "conf": "ok"
          },
          {
            "raw": "7000",
            "value": 7000.0,
            "conf": "ok"
          }
        ]
      },
      "pct_aid": {
        "value": 29.33,
        "n": 9,
        "raw": [
          {
            "raw": "0",
            "value": 0.0,
            "conf": "ok"
          },
          {
            "raw": "60%",
            "value": 60.0,
            "conf": "ok"
          },
          {
            "raw": "10%",
            "value": 10.0,
            "conf": "ok"
          },
          {
            "raw": "10%",
            "value": 10.0,
            "conf": "ok"
          },
          {
            "raw": "all of them as it is a free to the youth program",
            "value": null,
            "conf": "none"
          },
          {
            "raw": "0",
            "value": 0.0,
            "conf": "ok"
          },
          {
            "raw": "4%",
            "value": 4.0,
            "conf": "ok"
          },
          {
            "raw": "40",
            "value": 40.0,
            "conf": "ok"
          },
          {
            "raw": "100% of middle school students pay the reduced rate of $20 per sport to participate.  39% of high school students pay the reduced rate.",
            "value": 100.0,
            "conf": "approx"
          },
          {
            "raw": "40%",
            "value": 40.0,
            "conf": "ok"
          }
        ]
      },
      "aid_dollars": {
        "value": 539265.0,
        "n": 7,
        "raw": [
          {
            "raw": "$5,000",
            "value": 5000.0,
            "conf": "ok"
          },
          {
            "raw": "$0",
            "value": 0.0,
            "conf": "ok"
          },
          {
            "raw": "$36,800",
            "value": 36800.0,
            "conf": "ok"
          },
          {
            "raw": "no distribution of $",
            "value": null,
            "conf": "none"
          },
          {
            "raw": "0",
            "value": 0.0,
            "conf": "ok"
          },
          {
            "raw": "$2,465",
            "value": 2465.0,
            "conf": "ok"
          },
          {
            "raw": "More than $240,000",
            "value": 240000.0,
            "conf": "approx"
          },
          {
            "raw": "We don't disburse money to families.",
            "value": null,
            "conf": "none"
          },
          {
            "raw": "$255,000",
            "value": 255000.0,
            "conf": "ok"
          }
        ]
      },
      "coaches_worked": {
        "value": 1870.0,
        "n": 9,
        "raw": [
          {
            "raw": "2",
            "value": 2.0,
            "conf": "ok"
          },
          {
            "raw": "230",
            "value": 230.0,
            "conf": "ok"
          },
          {
            "raw": "N/A",
            "value": null,
            "conf": "none"
          },
          {
            "raw": "60",
            "value": 60.0,
            "conf": "ok"
          },
          {
            "raw": "about 60",
            "value": 60.0,
            "conf": "approx"
          },
          {
            "raw": "2 paid coaches.",
            "value": 2.0,
            "conf": "ok"
          },
          {
            "raw": "229",
            "value": 229.0,
            "conf": "ok"
          },
          {
            "raw": "300+",
            "value": 300.0,
            "conf": "approx"
          },
          {
            "raw": "887",
            "value": 887.0,
            "conf": "ok"
          },
          {
            "raw": "100+",
            "value": 100.0,
            "conf": "approx"
          }
        ]
      },
      "coaches_trained": {
        "value": 1538.0,
        "n": 8,
        "raw": [
          {
            "raw": "No formal training sports wise.",
            "value": null,
            "conf": "none"
          },
          {
            "raw": "0",
            "value": 0.0,
            "conf": "ok"
          },
          {
            "raw": "60",
            "value": 60.0,
            "conf": "ok"
          },
          {
            "raw": "about 60",
            "value": 60.0,
            "conf": "approx"
          },
          {
            "raw": "2 coaches, a 3rd will be starting in 2 weeks.",
            "value": 2.0,
            "conf": "approx"
          },
          {
            "raw": "229",
            "value": 229.0,
            "conf": "ok"
          },
          {
            "raw": "200+",
            "value": 200.0,
            "conf": "approx"
          },
          {
            "raw": "887",
            "value": 887.0,
            "conf": "ok"
          },
          {
            "raw": "100+",
            "value": 100.0,
            "conf": "approx"
          }
        ]
      }
    },
    "DC||T1": {
      "youth_served": {
        "value": null,
        "n": 0,
        "raw": []
      },
      "pct_aid": {
        "value": null,
        "n": 0,
        "raw": []
      },
      "aid_dollars": {
        "value": null,
        "n": 0,
        "raw": []
      },
      "coaches_worked": {
        "value": 2658.0,
        "n": 23,
        "raw": [
          {
            "raw": "3",
            "value": 3.0,
            "conf": "ok"
          },
          {
            "raw": "59",
            "value": 59.0,
            "conf": "ok"
          },
          {
            "raw": "0",
            "value": 0.0,
            "conf": "ok"
          },
          {
            "raw": "75",
            "value": 75.0,
            "conf": "ok"
          },
          {
            "raw": "6",
            "value": 6.0,
            "conf": "ok"
          },
          {
            "raw": "0",
            "value": 0.0,
            "conf": "ok"
          },
          {
            "raw": "25 paid and volunteer",
            "value": 25.0,
            "conf": "ok"
          },
          {
            "raw": "9",
            "value": 9.0,
            "conf": "ok"
          },
          {
            "raw": "3 including myself; volunteer",
            "value": 3.0,
            "conf": "ok"
          },
          {
            "raw": "25",
            "value": 25.0,
            "conf": "ok"
          },
          {
            "raw": "200",
            "value": 200.0,
            "conf": "ok"
          },
          {
            "raw": "20",
            "value": 20.0,
            "conf": "ok"
          },
          {
            "raw": "30",
            "value": 30.0,
            "conf": "ok"
          },
          {
            "raw": "2",
            "value": 2.0,
            "conf": "ok"
          },
          {
            "raw": "30",
            "value": 30.0,
            "conf": "ok"
          },
          {
            "raw": "30",
            "value": 30.0,
            "conf": "ok"
          },
          {
            "raw": "LPTM sub contracts with SOUL Programs, a fellow FFC Partner to access coaches for Basketball & Beyond",
            "value": null,
            "conf": "none"
          },
          {
            "raw": "5",
            "value": 5.0,
            "conf": "ok"
          },
          {
            "raw": "1200+ volunteers",
            "value": 1200.0,
            "conf": "approx"
          },
          {
            "raw": "20",
            "value": 20.0,
            "conf": "ok"
          },
          {
            "raw": "853",
            "value": 853.0,
            "conf": "ok"
          },
          {
            "raw": "25",
            "value": 25.0,
            "conf": "ok"
          },
          {
            "raw": "35",
            "value": 35.0,
            "conf": "ok"
          },
          {
            "raw": "3",
            "value": 3.0,
            "conf": "ok"
          }
        ]
      },
      "coaches_trained": {
        "value": 3153.0,
        "n": 23,
        "raw": [
          {
            "raw": "5",
            "value": 5.0,
            "conf": "ok"
          },
          {
            "raw": "24",
            "value": 24.0,
            "conf": "ok"
          },
          {
            "raw": "0",
            "value": 0.0,
            "conf": "ok"
          },
          {
            "raw": "20",
            "value": 20.0,
            "conf": "ok"
          },
          {
            "raw": "1",
            "value": 1.0,
            "conf": "ok"
          },
          {
            "raw": "1,,300",
            "value": 1300.0,
            "conf": "ok"
          },
          {
            "raw": "25",
            "value": 25.0,
            "conf": "ok"
          },
          {
            "raw": "4",
            "value": 4.0,
            "conf": "ok"
          },
          {
            "raw": "Formally? 0.",
            "value": 0.0,
            "conf": "ok"
          },
          {
            "raw": "35",
            "value": 35.0,
            "conf": "ok"
          },
          {
            "raw": "200",
            "value": 200.0,
            "conf": "ok"
          },
          {
            "raw": "2",
            "value": 2.0,
            "conf": "ok"
          },
          {
            "raw": "30",
            "value": 30.0,
            "conf": "ok"
          },
          {
            "raw": "N/a",
            "value": null,
            "conf": "none"
          },
          {
            "raw": "30",
            "value": 30.0,
            "conf": "ok"
          },
          {
            "raw": "30",
            "value": 30.0,
            "conf": "ok"
          },
          {
            "raw": "5",
            "value": 5.0,
            "conf": "ok"
          },
          {
            "raw": "2",
            "value": 2.0,
            "conf": "ok"
          },
          {
            "raw": "1200+",
            "value": 1200.0,
            "conf": "approx"
          },
          {
            "raw": "0",
            "value": 0.0,
            "conf": "ok"
          },
          {
            "raw": "219",
            "value": 219.0,
            "conf": "ok"
          },
          {
            "raw": "15",
            "value": 15.0,
            "conf": "ok"
          },
          {
            "raw": "6",
            "value": 6.0,
            "conf": "ok"
          },
          {
            "raw": "0",
            "value": 0.0,
            "conf": "ok"
          }
        ]
      }
    }
  }
};
